[package]
name = "imgui-sapp"
version = "0.2.0"
authors = ["Daniel Ludwig <codi@code-disaster.com>"]

[dependencies]
sokol = { path = "../../sokol" }
sokol-imgui = { path = "../../sokol-imgui" }
imgui-sys = "0.0.21"
