[package]
name = "sokol"
version = "0.1.0"
authors = ["Daniel Ludwig <codi@code-disaster.com>"]
edition = "2018"

build = "build.rs"

[dependencies]
bitflags = "1.0.4"

[build-dependencies]
cc = "1.0.25"
